apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  labels:
    kf-name: my-kubeflow
    label-one: value-one
  name: my-kubeflow-ip
  namespace: mlops-312413
spec:
  addressType: EXTERNAL
  description: Static IP for Kubeflow ingress.
  ipVersion: IPV4
  location: global
