apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/disable-dependent-services: "false"
  labels:
    kf-name: my-kubeflow
  name: meshtelemetry.googleapis.com
  namespace: mlops-312413
