apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: my-kubeflow-storage-metadata-store # {"$kpt-set":"name-storage-metadata-store"}
spec:
  location: us-east1 # {"$kpt-set":"location"}
  size: 20
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: my-kubeflow-storage-artifact-store # {"$kpt-set":"name-storage-artifact-store"}
spec:
  location: us-east1 # {"$kpt-set":"location"}
  size: 200
